version: "3.1"

services:
  dstserver:
    build: .
    ports:
      - "11000:11000/udp"
    volumes:
      - "./config:/home/linuxgsm/config"
    environment:
      CLUSTER_TOKEN: ${CLUSTER_TOKEN}
    dns:
      - ${DNS_SERVER}
