version: "3.1"

services:
  dstserver:
    build: .
    ports:
      - "11000:11000/udp"
    environment:
      CLUSTER_TOKEN: ${CLUSTER_TOKEN}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
